services:
  backend:
    build: ./backend
    ports:
      - "4567:4567"
    environment:
      - RACK_ENV=development
    volumes:
      - ./backend:/app
      - backend-data:/app/data
      - logs:/app/logs
    command: ["bundle", "exec", "ruby", "app.rb", "-o", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/api/dashboard/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:4567
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend-data:
  logs: